### ISSUE TITLE
MainStoryboard_***.storyboard can't be loaded in Xcode 6.1.3

### ISSUE THREAD

**Issue by longst** [forexample/testapp#1]
I always experienced "The document "MainStoryboard_***.storyboard" could not be opened. Unrecognized file content"  I have been trying to change configuration and cmakelists.txt files. but I didn't find a solution yet.. I wonder if you happen to have idea about this issue please?

**Comment by ruslo** [comment]
@longst Hi, what version of Xcode and CMake are you using?

**Comment by ruslo** [comment]
Works fine for me with CMake 3.2.1 (from brew) and Xcode 6.2 and 6.1.1.

**Comment by ruslo** [comment]
http://stackoverflow.com/questions/30150702/cmake-xcode-project-storyboard-can-not-be-loaded

**Comment by ruslo** [comment]
@longst Closing this one. Let me know if you have any question if future.
